### ISSUE TITLE
plugin doesn't work

### ISSUE THREAD

**Issue by liho26** [marcopompili/django-instagram#10]
Hi Marco,
I following your instructions. All dependies installed. DB synchronized. 
I copied and pasted code from "Usage" section. And I getting error:
**Invalid block tag on line 5: 'instagram_user_recent_media'. Did you forget to register or load this tag?**
What should I do now?

**Comment by dimkoug** [comment]
in your template you have to add 

{% load instagram_client %}

{% instagram_user_recent_media  instagram_user_account  %}

and then 

    <div class="row">
      {% for media in recent_media %}
      <div class="col instagram">
        <a href="https://www.instagram.com/p/{{ media.code }}" target="_blank" ><img src="{{ media.thumbnail_src }}" /></a>
      </div>
      {% endfor %}
    </div>
