### ISSUE TITLE
KeyError 'user"

### ISSUE THREAD

**Issue by linneudm** [marcopompili/django-instagram#14]
Unexpectedly an application started to display the following error:

```
KeyError at /
'user'
```

`[...] python2.7 / site-packages / django_instagram / templatetags / instagram_client.py in get_profile_media, line 23 `

`[...] python2.7 / site-packages / django_instagram / templatetags / instagram_client.py in get_profile_media`

`return profile ['entry_data'] ['ProfilePage'] [page] ['user'] ['media'] ['nodes']`

Anyone else with this issue?

**Comment by citmusa** [comment]
Me.
User info is now nested under `graphql`
so
instagram_client.py L:23
`profile['entry_data']['ProfilePage'][page]['user']['media']['nodes'] ` should be `profile['entry_data']['ProfilePage'][page]['graphql']['user']['media']['nodes']`

**Comment by linneudm** [comment]
`profile['entry_data']['ProfilePage'][page]['graphql']['user']['media']['nodes']`

This dont works?

**Comment by citmusa** [comment]
This does.
```
edges = profile['entry_data']['ProfilePage'][page]['graphql']['user']['edge_owner_to_timeline_media']['edges']
return [edge['node'] for edge in edges]
```

**Comment by linneudm** [comment]
Thank you for help.

**Comment by ezawadzki** [comment]
The marcopompili/django-instagram(master) avoid the user error but no pictures are shown.
The pull request #15 allow to show thumbnails. @marcopompili can you merge de the pull request please ?

**Comment by marcopompili** [comment]
Merged, gonna test it and hopefully publish a new package.

**Comment by ezawadzki** [comment]
Thank you @marcopompili and @citmusa  !
