### ISSUE TITLE
Media Url

### ISSUE THREAD

**Issue by ezawadzki** [marcopompili/django-instagram#16]
The media url is wrong in example since Instagram has change his json structure.
Instead of using :

`{{ media.display_src }}
`

Please use :

`{{ media.shortcode }}
`

Full working example :

```
{% load instagram_client %}

{% instagram_user_recent_media intel %}

<div id="django_recent_media_wall">
  {% for media in recent_media %}
    <div class="django_instagram_media_wall_item">
      <a href="{{ media.shortcode }}" target="_blank" title="{{ media.caption }}">
        <img src="{{ media.thumbnail_src }}"/>
        <span>{{ media.caption }}</span>
      </a>
    </div>
  {% endfor %}
</div>
```

**Comment by linneudm** [comment]
I was searching for it. Thank you so much! How to debug the variables from `media`?

**Comment by Stocked** [comment]
this worked as caption for me 

{{ media.edge_media_to_caption.edges.0.node.text }}

**Comment by marcopompili** [comment]
`{{ media.edge_media_to_caption.edges.0.node.text }}` Jesus that looks terrible.

Fixing the example.

**Comment by marcopompili** [comment]
The correct way to use a shortcode is this: `https://instagram.com/p/{{ media.shortcode }}`

**Comment by anoleose** [comment]
The app does not display images in production using heroku 
is there anybody can know why?

**Comment by anoleose** [comment]
production_settings.py for media files  and staticfiles  i am using AWS S3

AWS_ACCESS_KEY_ID = os.environ.get('AWS_ACCESS_KEY_ID')
AWS_SECRET_ACCESS_KEY = os.environ.get('AWS_SECRET_ACCESS_KEY')
AWS_STORAGE_BUCKET_NAME = os.environ.get('AWS_STORAGE_BUCKET_NAME') 

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, "static", "media")
--------------------------------------------------------------------------------------------

local_settings.py
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, "static", "media")
locally the instagram scraper displays images

**Comment by SimonHurst** [comment]
Are you using any middleware?

**Comment by BuiltWithLogic** [comment]
consider using https://devcenter.heroku.com/articles/s3-upload-python <https://devcenter.heroku.com/articles/s3-upload-python> or look up django and s3

You’re using Heroku you don’t have the smae ontrol you do with your own server, plus downloaded content shouldn’t be on the single dyno… as it’ll brake if you fire up more or just break in general.

**Comment by anoleose** [comment]
I am whitenoise middleware
