### ISSUE TITLE
How to fetch all the posts from the instagram

### ISSUE THREAD

**Issue by Neerajkashyap** [marcopompili/django-instagram#18]
Hi, I am using this package in my django project. And i want to know how can i fetch all the posts from instagram, as currently i am only able to fetch recent 12 posts. Thanks in advance.

**Comment by ans2human** [comment]
@Neerajkashyap i also have the same issue and in addition to that how can i get likes and comments of my posts ?

**Comment by marcopompili** [comment]
It's not possible since posts after the first 12 need to be stream loaded, they don't actually appear on  page.

**Comment by Abdullahabid3691** [comment]
How to use a variable in the django-instagram app : {% instagram_user_recent_media username %}?

**Comment by Abdullahabid3691** [comment]
I pass a variable to the template that I call username. It contains the username of the instagram user. When I try to do this for exemple : <p>{{ username }}</p>. It works perfectly. It's displaying the good username.

But when I use the tag {% instagram_user_recent_media username %}, it takes username as a string. So the app search on Instagram with the username "username". Obviously it don't find anything. I also tried to do that : {% instagram_user_recent_media {{ username }} %}

**Comment by marcopompili** [comment]
@Abdullahabid3691 At the moment you can't. I'm going to close this because your question is off-Topic, if you want you can open a new Issue so i can tag it as `enhancement`.
