### ISSUE TITLE
README.rst is out of date

### ISSUE THREAD

**Issue by Wooble** [marcopompili/django-instagram#19]
The ReST version of the README (which appears on pypi) references an admin page that no longer exists, which is very confusing.

**Comment by marcopompili** [comment]
What admin page? The page on pypi is up to date: https://pypi.org/project/django-instagram/

**Comment by Wooble** [comment]
The README.rst contains the text

**Go to the Django Instagram administration panel and click on “Get Access Token” button to receive your access token from Instagram. Then copy and paste it to the configuration field and save.

Remember to be logged in with the Instagram account that you want to get the access token for.**


which is not in README.md and which appears to be incorrect. This text appears on oypi, not on github's default doc display on the project page.

**Comment by marcopompili** [comment]
Sorry, I missed it, fixing.

**Comment by marcopompili** [comment]
Version 0.3.1 is on pipy.
