### ISSUE TITLE
Instagram blocks content loading

### ISSUE THREAD

**Issue by ggjersund** [marcopompili/django-instagram#21]
So there seems to be an update that disallows crawled images from Instagram.
I get "content can load" even though the images appear in the browser normally.

**Comment by marcopompili** [comment]
Care to expand on the problem? You are very vague. Also I tested the extension and it still works properly, remember that this extension cannot work on private profiles.

**Comment by ggjersund** [comment]
@marcopompili Seems like its fixed at my end as well. Can't replicate it anymore. Must have been some older browser version or some change by Instagram. I'll close the issue as resolved.
