### ISSUE TITLE
image could not be load in html

### ISSUE THREAD

**Issue by jeffersonkr** [marcopompili/django-instagram#23]
using a tutorial and any username with is public images do not appears

![Captura de tela de 2020-01-05 08-57-23](https://user-images.githubusercontent.com/36552733/71779869-7ead2680-2f99-11ea-828f-e2dac7154532.png)

and when i just open the same url into another the image appears without any problem

**Comment by Rewzaw** [comment]
have you added 'sorl.thumbnail' to your installed apps in settings.py?
