### ISSUE TITLE
Invalid client ID

### ISSUE THREAD

**Issue by blackwiz4rd** [marcopompili/django-instagram#7]
Hi,
when I press on get token (after logging in) I get this error message:
{"error_type": "OAuthException", "code": 400, "error_message": "Invalid Client ID"}

https://www.instagram.com/oauth/authorize/?client_id=5668831cb13b4876a63fa53fe768927e&redirect_uri=http://www.emarcs.net/instagram/&response_type=code

http://www.emarcs.net/instagram/ returns 404

any way to fix it? 
Thanks

**Comment by marcopompili** [comment]
You installed an old version, for installing the current version:

`pip install django-instagram==0.2.0a1`
